pmc_8881_RNm1: PMC - RN - Receita Nominal por Setor - Mensal,
pmc_8881_RNm12: PMC - RN - Receita Nominal por Setor - Acumulado 12 meses,
pmc_8881_RNAcM1: PMC - RN - Variação Mensal da Receita Nominal,
pmc_8881_RNAcM12: PMC - RN - Variação Acumulada da Receita em 12 meses,
pmc_8883_RNAtvM1: PMC - RN - Receita Nominal por Atividade - Mensal,
pmc_8883_RNAtvM12: PMC - RN - Receita Nominal por Atividade - Acumulado 12 meses,
pmc_8883_RNAtvAcM1: PMC - RN - Variação Mensal da Receita por Atividade,
pmc_8883_RNAtvAcM12: PMC - RN - Variação Acumulada da Receita por Atividade em 12 meses,
pms_8688_RNm1: PMS - RN - Volume de Serviços por Setor - Mensal,
pms_8688_RNm12: PMS - RN - Volume de Serviços - Acumulado 12 meses,
pms_8688_RNAcM1: PMS - RN - Variação Mensal do Volume de Serviços,
pms_8688_RNAcM12: PMS - RN - Variação Acumulada do Volume de Serviços - 12 meses,
pms_8693_RNLocm1: PMS - RN - Volume de Serviços por Localidade - Mensal,
pms_8693_RNLocm12: PMS - RN - Volume de Serviços por Localidade - Acumulado 12 meses,
pms_8693_RNAcLocm1: PMS - RN - Variação Mensal por Localidade,
pms_8693_RNAcLocm12: PMS - RN - Variação Acumulada por Localidade - 12 meses,
pnadc_4093_ocupacaoTri: PNAD Contínua - Ocupação no Brasil - Trimestral,
pnadc_4093_desocupacaoTri: PNAD Contínua - Desocupação no Brasil - Trimestral,
pnadc_4093_informalidadeTri: PNAD Contínua - Informalidade no Trabalho - Trimestral,
transacaoCartao: Transações de Cartão - Volume por Bandeira e Função,
ipca_7060_brasil: IPCA - Brasil - Índice Nacional de Preços ao Consumidor - Mensal,
ipca_7060_recife: IPCA - Recife - Inflação Local - Mensal,
ipca_7060_AcBrasil: IPCA - Brasil - Inflação Acumulada no Ano,
ipca_7060_Ac12Brasil: IPCA - Brasil - Inflação Acumulada em 12 Meses
