# ----------------------------------------------------------------
# PESQUISA MENSAL DE COMÉRCIO (PMC) - IBGE
# ----------------------------------------------------------------
pmc_8881_RNm1, RNm12, RNAcM1, RNAcM12: "PMC - Variação da receita nominal do comércio varejista ampliado, por localidade. Inclui atividades de Veículos, Motocicletas, partes e peças e de Material de construção."
pmc_8883_RNAtvM1, RNAtvM12, RNAtvAcM1, RNAtvAcM12: "PMC - Variação da receita nominal do comércio varejista ampliado, por atividade e localidade. Detalha os setores do comércio."

# ----------------------------------------------------------------
# PESQUISA MENSAL DE SERVIÇOS (PMS) - IBGE
# ----------------------------------------------------------------
pms_8688_RNm1, RNm12, RNAcM1, RNAcM12: "PMS - Variação da receita nominal de serviços, por categoria de serviço. Abrange o setor de serviços em nível nacional."
pms_8693_RNLocm1, RNLocm12, RNAcLocm1, RNAcLocm12: "PMS - Variação da receita nominal de serviços, por estado e categoria. Detalha o desempenho dos serviços nas Unidades da Federação."

# ----------------------------------------------------------------
# PESQUISA NACIONAL POR AMOSTRA DE DOMICÍLIOS CONTÍNUA (PNADC) - IBGE
# ----------------------------------------------------------------
pnadc_4093_ocupacaoTri, desocupacaoTri, informalidadeTri: "PNADC - Indicadores trimestrais do mercado de trabalho, por estado. Inclui taxas de ocupação, desocupação (desemprego) e informalidade."

# ----------------------------------------------------------------
# ÍNDICE NACIONAL DE PREÇOS AO CONSUMIDOR AMPLO (IPCA) - IBGE
# ----------------------------------------------------------------
ipca_7060_brasil, recife, AcBrasil, Ac12Brasil: "IPCA - Variação mensal e acumulada de preços (inflação) para o Brasil e Recife, detalhada por grupos, subgrupos e itens de consumo."

# ----------------------------------------------------------------
# TRANSAÇÕES COM CARTÃO - BANCO CENTRAL (BACEN)
# ----------------------------------------------------------------
transacaoCartao: "Transações com cartões de crédito, débito e pré-pago. Contém dados trimestrais sobre quantidade de cartões, número e valor de transações nacionais e internacionais, por bandeira e função (crédito/débito)."